### ISSUE TITLE
contents.matchAll is not a function

### ISSUE THREAD

**Issue by brunoocasali** [NullVoxPopuli/ember-component-stats#1]
Hey @NullVoxPopuli I've got this error when running `ember-component-stats` inside my ember app folder:

```
➜  dash git:(master) npm -v                                     
6.13.1
➜  dash git:(master) node -v                                    
v10.13.0
➜  dash git:(master) yarn --version                             
1.19.1
➜  dash git:(master) ember -v                                   
ember-cli: 3.14.0
node: 10.13.0
os: darwin x64
```

This error repeats:
```js
 { name: 'survey.js',
    error:
     TypeError: contents.matchAll is not a function
         at componentsInContent (/Users/bruno/.nvm/versions/node/v10.13.0/lib/node_modules/ember-component-stats/dist/utils.js:11:28)
         at gatherComponentInvocations (/Users/bruno/.nvm/versions/node/v10.13.0/lib/node_modules/ember-component-stats/dist/gather.js:97:53)
         at gatherInfoOnFile (/Users/bruno/.nvm/versions/node/v10.13.0/lib/node_modules/ember-component-stats/dist/gather.js:41:3)
         at Walker.file (/Users/bruno/.nvm/versions/node/v10.13.0/lib/node_modules/ember-component-stats/dist/index.js:39:36)
         at Walker.emit (events.js:182:13)
         at Object.emitSingleEvents [as emitNodeType] (/Users/bruno/.nvm/versions/node/v10.13.0/lib/node_modules/ember-component-stats/node_modules/walk/lib/node-type-emitter.js:58:13)
         at Walker._wLstatHandler (/Users/bruno/.nvm/versions/node/v10.13.0/lib/node_modules/ember-component-stats/node_modules/walk/lib/walk.js:88:19)
         at Walker._wFilesHandler (/Users/bruno/.nvm/versions/node/v10.13.0/lib/node_modules/ember-component-stats/node_modules/walk/lib/walk.js:112:10)
         at Walker.wFilesHandlerWrapper (/Users/bruno/.nvm/versions/node/v10.13.0/lib/node_modules/ember-component-stats/node_modules/walk/lib/walk.js:23:10)
         at Array.forEach (<anonymous>) } ]
```

**Comment by NullVoxPopuli** [comment]
Does it work with node 12? I think node 12 is required

**Comment by brunoocasali** [comment]
@NullVoxPopuli yeah, thats it! Installed with 12 version and worked!
